name: 'Submit Maven Dependencies Snapshot'

on:
  workflow_call:
    inputs:
      runs-on:
        description: |
          The type of machine to run the job on. Must be provided as a stringified list (e.g. `runs-on: '["ubuntu-latest","self-hosted"]'`)
        required: true
        type: string
      directory:
        description: 'The directory that contains the pom.xml that will be used to generate the dependency graph from'
        default: '.'
        required: false
        type: string
      mvn-version:
        description: |
          The Maven version used for the execution. You can specify minor or patch version (3.9 or 3.9.1). Default : 3.9
        required: false
        type: number
        default: 3.9
      jdk-version:
        description: |
          The JDK version to use for the build.
        default: 21
        required: false
        type: number
      mvn-additional-arguments:
        description: |
          The additional arguments to pass to the Maven invocation. You can use this to specify a custom profile for example.

          If you wish to exclude certain modules from the scan, pass: -Dexcludes=groupId:artifactId:type:classifier

        required: false
        type: string

jobs:
  submit-dependencies:
    name: Submit dependencies

    runs-on: ${{ fromJson(inputs.runs-on) }}

    container:
      image: maven:${{ inputs.mvn-version }}-eclipse-temurin-${{ inputs.jdk-version }}

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Submit Dependency Snapshot
        uses: advanced-security/maven-dependency-submission-action@v4
        with:
          directory: ${{ inputs.directory }}
          maven-args: ${{ inputs.mvn-additional-arguments }} -Dscopes=compile,provided,runtime,system
