name: 'Submit Maven Dependencies Snapshot'

on:
  workflow_call:
    inputs:
      runs-on:
        description: |
          The type of machine to run the job on. Must be provided as a stringified list (e.g. `runs-on: '["ubuntu-latest","self-hosted"]'`)
        required: true
        type: string
      directory:
        description: 'The directory that contains the pom.xml that will be used to generate the dependency graph from'
        default: '.'
        required: false
        type: string
      mvn-version:
        description: |
          The Maven version used for the execution. You can specify minor or patch version (3.9 or 3.9.1). Default : 3.9
        required: false
        type: number
        default: 3.9
      jdk-version:
        description: |
          The JDK version to use for the build.
        required: true
        type: number

jobs:
  submit-dependencies:
    name: Submit dependencies

    runs-on: ${{ fromJson(inputs.runs-on) }}

    container:
      image: maven:${{ inputs.mvn-version }}-eclipse-temurin-${{ inputs.jdk-version }}

    permissions:
      actions: read
      contents: write
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Submit Dependency Snapshot
        uses: advanced-security/maven-dependency-submission-action@v3
        with:
          directory: ${{ inputs.directory }}
